### ISSUE TITLE
`make_base_discrete_laplace` -- Proof

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#114]

**Comment by Shoeboxam** [comment]
There are multiple approaches-
1. (implemented) A constant-time execution mode with clipping bounds. The clipping bounds makes it possible to bound the runtime of sampling from the two-sided geometric, by censoring the tails. This involves two clamps, one on the input, one on the output.
2. (not implemented) A tweak on 1. that doesn't clamp the input. This adds a delta term- the accumulated probability in the last uncensored bin.
3. (implemented) A mode without timing protections that simulates draws from the un-censored two-sided geometric. You can view this a special case of 1., where the clamping bounds are T::MIN and T::MAX. The input and output are "clamped" to what numbers can be represented by T. Constant-time execution is not available without bounds because it would take an unrealistic `2^(T::BIT_DEPTH)` biased draws to guarantee constant-time execution.
4. If the bounds are large, it would be possible to reduce execution time by reducing the granularity of the output.

**Comment by Shoeboxam** [comment]
In the current state of the library, there are two algorithms. 
`make_base_discrete_laplace_linear` covers (1) and (3).
`make_base_discrete_laplace_cks20` is a more efficient sampler when scale > 10, working on bignums.

To prove `make_base_discrete_laplace`, we must prove both of these constituent algorithms.

**Comment by raprasad** [comment]
Closing for #1314
