### ISSUE TITLE
Add `Supporting Elements` section?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1189]
>  Is the `Supporting Elements` section applicable here?

_Originally posted by @mccalluc in https://github.com/opendp/opendp/pull/958#discussion_r1467864648_

If it's not applicable, I should try to understand why.

**Comment by Shoeboxam** [comment]
You were asking why the section is missing here-- it's because that information is extracted from the return type of the function, and in this case, the return type is `AnyMeasurement`, which doesn't have that information. In order to make FFI possible, combinators make much more use of type-erasure, which causes this information to go missing. I think it could be written manually in these cases.

**Comment by mccalluc** [comment]
Thanks for the explanation. I wouldn't want to worry about trying to keep hand-written API docs in sync, so I'll close this... but feel free to reopen if you feel that it would be good to add these.
