### ISSUE TITLE
Context API: Return type hint on Query.compositor should be "Query"

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1376]

**Comment by mccalluc** [comment]
After talking: we think it should be as simple as changing the return type hint, ie, we don't think there are problems with the runtime code... but then why isn't mypy complaining about the current state? So the right path is probably:
- Get mypy to complain about the current typing. (Add more typing elsewhere? Or maybe there's a bug, and we're not returning what we think we are returning?)
- Then fix the typing here.

**Comment by mccalluc** [comment]
@Shoeboxam : So I can get mypy to complain by adding more typing, but I'm also wondering if the code is actually doing what we want:
```python
    def _compose_context(self, compositor) -> "Query" | "PartialChain":
        """Helper function for composition in a context."""
        if isinstance(self._chain, PartialChain):
            return PartialChain(lambda x: compositor(self._chain(x), self._d_in)) # pragma: no cover
        else:
            return compositor(self._chain, self._d_in)
```

The methods on `PartialChain` and `Query` are pretty different, in particular you can't release a `PartialChain`, so this causes a typing error in the tests.

I can imagine going a few different directions from here:
- Relying on `isinstance` can be an indication that we're not being sufficiently OO. Maybe `Query` should be subclassed, one when `_chain` is `Chain`, and another when it's `PartialChain`?
- Maybe we should do something other than return a `PartialChain` here?
- Since it's not exercised, and not part of the functionality required by the current typing, maybe we remove the `isinstance(self._chain, PartialChain)` branch entirely?
