### ISSUE TITLE
Context API: improved error message when compositor is not released

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1379]
Consider adding a new method to `class Query`:

```python
    def query(self):
        raise ValueError("Did you forget to call `.release()` on a compositor query?")
```

Meant to improve quality of error messages in cases where you do:
```python
subcontext = context.query().a().b().compositor(...)

subcontext.query().laplace().release()
```

Open to thoughts!

**Comment by mccalluc** [comment]
Conversely, adding that method changes something that could be caught by type checking to something that will only be caught at runtime. I also wonder if people are likely to rely on completion from the IDE, and then this may lead them in the wrong direction.

We might do something like this if it were a subclass, and a particular method hadn't been implemented, but otherwise as a developer aid I don't think it makes sense.

**Comment by mccalluc** [comment]
Mike: Found that at the end of the chain the type info wasn't there for useful feedback from IDE or mypy.

Root problem: need more typing?! Won't file an issue: We know it's a good thing to do.
