### ISSUE TITLE
Usability: API Function Documentation

### ISSUE THREAD

**Issue by chikeabuah** [opendp/opendp#1418]
<img width="641" alt="Screen Shot 2024-03-21 at 9 36 15 AM" src="https://github.com/opendp/opendp/assets/2280440/5dfa4448-6295-4479-ae63-18a0a33a2dc9">

Consider, documenting each API function on a separate page, along with examples and DP-specific advice.

From study "Evaluating the Usability of Differential Privacy Tools with Data Practitioners" by Ngong et al.

**Comment by mccalluc** [comment]
There are a couple separate issues here:
- Docs are searchable now, and hopefully it's easy to find the search? But I think they've been searchable for a while, so I'm not sure I understand the user's original problem.
- More examples in the API reference: This is hard, because the framework docs come from Rust. Could imagine adding logic to the docs-build to insert examples in the appropriate language, but it would add some complexity. Alternatively, could link to appropriate sections of the user guide from the API reference.
- Separately, we could have smaller pages, though I'm not sure this would be a big win. [Some options on SO](https://stackoverflow.com/questions/43357912/using-sphinx-to-automatically-generate-a-separate-document-for-each-function). FWIW, one function per page is the default for R docs.

**Comment by Shoeboxam** [comment]
* Agreed, we've always had search.
* This is why there's such a harsh division between the user guide and API docs. The user guide is hand-written and should contain examples. Given that API docs are mostly generated, it's easy to go from the user guide to the API docs, but difficult to go from the API docs to the user guide.
* Separate pages for each constructor make sense, as the API docs are not meant to be read top-to-bottom.
* I would love to have more guidance on DP and I think the OpenDP Project is well-suited to do this. This was the reason for writing the first look at DP notebook, programming framework notebook and that more mathematical getting started notebook. I've always hoped that the educational working group might help produce some materials for this, but in the meantime I've gradually worked on adding guidance into the OpenDP docs.

**Comment by Shoeboxam** [comment]
There's a fair amount we can do to reduce the surface area to document, as well. We could consider removing transformation constructors like casting, imputation, b_ary_tree, quantile scoring, lipschitz mul, and all the transformation aggregators in favor of rolled-up all-in-one measurement constructors. While on the one hand this would reduce the flexibility of the library, it would make it easier to see the forest from the trees.

**Comment by mccalluc** [comment]
There will always be more work here, but at a high level things have improved a lot. 
- Search is working.
- we have some python-specific examples in the API reference, and want to add more for the most highly visible ones: #1545
- The notebooks that are going in now will provide a lot of examples.
- I think that docs per-module rather than per-function are ok, but if anyone feels strongly, can revisit.

New granular issues are welcome, but I think this can be closed.
