### ISSUE TITLE
Unify dataset distances as SymmetricDistance

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#156]
After some discussion, we've decided to unify treatment of dataset distances:

* Keep the name `SymmetricDistance` (do not rename to `SymmetricDifference`).
* Rename `HammingDistance` to `SubstituteDistance`.
* Standardize on `SymmetricDistance` for all appropriate constructors. Remove dispatch for `SubstituteDistance` (but keep the type).
* For applications that desire it, provide a conversion constructor that can cast `Transformation<_, _, SymmetricDistance, _>` to `Transformation<_, _, SubstituteDistance, _>` with a 1/2 stability factor.
* Aside: For things like `make_sum`, we don't try to model the case of (datasets of unknown but same size, neighbors differ by substitutions). This is because it's impossible to compare datasets of different sizes (infinite distance).

**Comment by Shoeboxam** [comment]
About merging Substitute and Symmetric distance. There are four situations where relations may differ:
```
+------------+---------+-------+
|            | unsized | sized |
+------------+---------+-------+
| symmetric  | 1       | 2     |
+------------+---------+-------+
| substitute | 3       | 4     |
+------------+---------+-------+
```
Case 1 is the standard add/remove sensitivity proof.   
Case 2 is a restricted sensitivity variation where n is known and the symmetric distance must be even.  
Case 3 is poorly-constructed and doesn't hold meaning. If we don't know dataset size, then we should be able to consider datasets that differ in size as neighbors. The metric is not suited for the domain, and leads to strange situations like sensitivity-zero count queries.  
Case 4 is always half of case 1. Since the symmetric distance is even, this still divides nicely on integer sensitivities. It is sufficient to capture substitute distance via a transformation that converts to symmetric distances at 2*d_in.

Since case 3 is not applicable, and case 4 can be captured with a single transformation, we might as well simplify by not implementing different versions of functions for substitute distances. This leaves us with one dataset metric, which allows us to drop the metric type argument completely on most transformation constructors and APIs across the library.
