### ISSUE TITLE
Tighter output domain bounds if `size` is specifed?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1658]
In this case:
```
>>> bounded_sum = dp.t.make_sum(
...     input_domain=dp.vector_domain(dp.atom_domain(bounds=(0, 1)), size=2),
...     input_metric=dp.symmetric_distance(),
... )
>>> bounded_sum.output_domain
AtomDomain(T=i32)
```
I think we could infer `[0, 2]` as a bound on the output domain... Assuming that's correct, would it be useful?

**Comment by Shoeboxam** [comment]
We don't currently have a need for it, which is why we don't preserve bounds descriptors through the sum transformation. In earlier iterations of the library design, it would be super inconvenient for the user to specify these bounds for the input domain to the noise perturbation measurements, in a way that would chain. This is now easier with partials.

One place where it would potentially be useful is in `make_lipschitz_mul`, which needs these bounds. Since `make_lipschitz_mul` is not typically user-facing, this hasn't been an issue, because these bounds are filled in by the rollup constructors `make_mean` and `make_variance`. Those rollup constructors compute these bounds and `make_lipschitz_mul` clamps to them. If we wanted to pull the clamp out of `make_lipschitz_mul`, we could now do so without impacting UX due to partials. We'd do this by moving the bounds computation from the rollup constructors to the `make_sum` or `make_sum_of_squared_deviances` constructors, respectively, and dropping the clamp in `make_lipschitz_mul`.

Generally speaking, I think it's better to handle these kinds of transformations outside the privacy boundary, so instead of updating `make_lipschitz_mul`, it would be better to add more general constructors that compute DP means and variances directly, and which employ post-processing instead.

**Comment by mccalluc** [comment]
Thanks for the explanation. In the end, it sounds like this is not something that would be useful, so I'll close?
