### ISSUE TITLE
Troubleshooting docs

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#222]
Place to collect install issues to move into a troubleshooting.md or documentation at some point.

error: `AttributeError: module 'enum' has no attribute 'IntFlag'`
solution: `pip3 uninstall -y enum34`

error: `error[E0658]: const generics are unstable`
solution: `rustup update`

**Comment by RoyRin** [comment]
Not an install issue, but in the[ getting started link](https://docs.opendp.org/en/stable/user/getting-started.html) :

`identity = make_identity(M=SubstituteDistance, T=str)`  should be : 
`identity = make_identity(M=SubstituteDistance, TA=str)`

Potentially the docs.opendp.org documentation could be moved to github, so that the community can directly push changes to improve it ( for example : [supporting elements](https://docs.opendp.org/en/stable/user/supporting-elements.html ) does not seem to have content).

**Comment by RoyRin** [comment]
I see this is also mentioned here : https://github.com/opendp/opendp/issues/268
looks like it resolved by pdurbin

**Comment by pdurbin** [comment]
@RoyRin yes! Very recently fixed in 22d9519 (which is to say that the docs are on GitHub and contributions are very welcome!). If you switch from "stable" to "latest" you can see the change:

- https://docs.opendp.org/en/stable/user/getting-started.html
- https://docs.opendp.org/en/latest/user/getting-started.html

As for pages without content, we're definitely aware of them. #261 is probably a good place to get an overview of the current efforts.

**Comment by Shoeboxam** [comment]
Instead of adding a troubleshooting docs page, I added a discussion category:
https://github.com/opendp/opendp/discussions/categories/error-index

Errors inside the library link to the relevant discussion.
The relevant discussion has a write-up on how to interpret the error and what to do to fix it.
