### ISSUE TITLE
Downcasting for Any* types

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#247]
Splitting the general aspects of type handling from #159 into a separate issue.

For some combinators like `make_population_amplification()`, we need a way to get from `AnyMeasurement` to something that can be handled by Rust functions.

**Comment by Shoeboxam** [comment]
Generally speaking, there are a lot of situations where it would be more ideal to leave the type as an Any* and implement traits for Any* types instead, by enclosing additional glue. The downside to this is that we've traditionally constructed glue when you do type erasure, which means all traits the Any* object captures must be included in the bounds whenever we do type erasure. This means there are global modifications to all constructors' trait bounds whenever you add a new trait bound requirement to an Any* type. 

A different approach is to lazily construct glue functions for the traits you need, as you need them, in the FFI layer. A nice side-effect is that we could drop the AnyMetricDistance and AnyMeasureDistance types, as the additional trait bounds they enclose are traits that you could lazily reconstruct on AnyObjects. 

The initial attempt looks like this:
```rust
#[derive(Clone, PartialEq)]
pub struct AnyMeasure {
    pub measure: AnyBoxClonePartialEq,
    pub distance_type: Type,
    pub population_amplification_glue: Option<Glue<fn(&AnyMeasure, &AnyObject, &AnyObject) -> AnyObject>>
}

impl AnyMeasure {
    pub fn new<M: 'static + Measure>(measure: M) -> Self {
        Self {
            measure: AnyBoxClonePartialEq::new_clone_partial_eq(measure),
            distance_type: Type::of::<M::Distance>(),
            population_amplification_glue: None
        }
    }

    pub fn has_population_amplification<M: 'static + AmplifiableMeasure>(&mut self) -> () {
        self.population_amplification_glue = Some(Glue::new(|self_: &Self, budget: &AnyObject, sampling_ratio: &AnyObject| -> AnyObject {
            let self_ = self_.downcast_ref::<M>().unwrap();
            let budget = budget.downcast_ref::<M::Distance>().unwrap();
            let sampling_ratio = sampling_ratio.downcast_ref::<M::Atom>().unwrap();
            AnyObject::new(self_.amplify(budget, sampling_ratio))
        }));
    }
}

impl AmplifiableMeasure for AnyMeasure {
    type Atom = AnyObject;
    fn amplify(&self, budget: &AnyObject, sampling_rate: &AnyObject) -> AnyObject {
        self.population_amplification_glue.as_ref().expect("missing amplify glue")(self, budget, sampling_rate)
    }
}
```

There's optional glue for population amplification, and in the calling code, you call `meas.output_measure.has_population_amplification()`.
I tried to avoid dispatch in this glue constructor, but it just pushes dispatch out into the measurement constructor. One positive about this approach (leaving types as Any*) is that the dispatch is a bunch of linear-time lookups O(tn) to build glue, instead of O(n^t).

**Comment by Shoeboxam** [comment]
We've generally moved forward from this by implementing traits on AnyObjects that handle downcasting. In #482 #233 #505.
