### ISSUE TITLE
Initial documentation

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#261]
High level list (can be split into smaller issues)

- [x] #265
- [x] #268
- [x] #269
- [x] #270
- [x] #271
- [x] #272
- [x] #273

**Comment by RoyRin** [comment]
Incredibly simple proposal:  OpenDP currently has some jupyter notebooks in `python/examples/`. It would be very easy to use [Binder](https://mybinder.org/) and include links to that from the documentation, making quick-starts even easier. (Binder will build and host docker containers that run jupyter notebooks, so that you can run them a webpage, without having to download everything and run jupyter yourself).

[OpenDP Binder Link](https://mybinder.org/v2/gh/opendp/opendp/HEAD)
