### ISSUE TITLE
Docs TOC/index convention

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#283]
From https://github.com/opendp/opendp/pull/278/files#r705851583

We should figure out a convention for the local TOC/index in docs, and make a pass to get everything in sync (if necessary).

**Comment by pdurbin** [comment]
If we decide we want to stick with...

```
.. contents:: |toctitle|
        :local:
```

... on every page we should probably mention this explicitly at https://docs.opendp.org/en/stable/developer/logistics.html#documentation (I think this is the main area where we talk about docs). That's what we do for Dataverse: https://guides.dataverse.org/en/5.6/developers/documentation.html#table-of-contents

Otherwise we're relying to people picking up the convention from other pages (which I'm sure they'd do to some extent.)
