### ISSUE TITLE
README "style guide" for OpenDP repos

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#371]
- Style guide for repositories/frontpage README! 
- Consistency around items such as badges for licensing, CI, python versioning, etc.
- Recommended logos, how to reference the overall OpenDP project, communication channels, etc.

(Note, the issue is in opendp/opendp, not sure if this is the appropriate place for the style guide)

**Comment by mccalluc** [comment]
I think we like what we're doing with our readme, and would encourage new projects under the same umbrella to emulate it. (If there are things we don't like, then let's fix them here!)

One thing we're missing is the logo. Since the readme is also used for the pypi docs, it should be an absolute url. Quick PR coming in...
