### ISSUE TITLE
Selecting a column not in the dataframe throws an exception when invoked

### ISSUE THREAD

**Issue by samhaney** [opendp/opendp#419]
**Describe the bug**
Selecting a column not in the dataframe throws an exception when invoked. Transformations should produce an output in the output domain when given an input in the input domain for the privacy guarantee to hold.

There is no immediate privacy vulnerability, because as far as I know there is no transformation in OpenDP that can produce a dataframe where the existence of some column depends on the private data. However, I still think this is a bug, because a transformation that creates a column depending on the data is valid for the privacy framework, and combined with `make_select_column` results in unbounded privacy loss.

**To Reproduce**
```
from opendp.trans import make_select_column, make_split_dataframe
from opendp.mod import enable_features

enable_features('contrib')

columns = ["A", "B"]
data = """1,2
3,4
"""
transformation = make_split_dataframe(
    separator=",", col_names=columns
) >> make_select_column(key="C", TOA=str)
transformation(data)
```

- Observed behavior: The transformation throws an error when called on the data.
- Expected behavior: The transformation runs without error on the data and produces a valid output in the output domain, or the transformation throws an error when it is constructed (i.e. the column names are part of the domain).

**Comment by raprasad** [comment]
See also #420

(Thanks, @samhaney)

**Comment by Shoeboxam** [comment]
We've been intentional about defining the domain in such a way that the column set is always known-- passed into a constructor, and being a part of the definition of a dataframe domain.

The way we would throw an error at construction-time is by including column names in the dataframe domain. This hasn't been very attractive because you'd then need to pass column names into every dataframe transformation constructor, which would make the library more difficult/verbose to use.

However, going forward, we've been talking about ways we might automatically forward domain descriptors to the next transformation (see #664). If we had this kind of system in-place, then the library wouldn't take this usability hit.

In the current state of the library, we haven't acted on this because it both hasn't been a privacy violation, and because I'd rather not take this usability hit. However, if we adopt #664, it becomes more favorable to add domain names to dataframe domains, and move this error to construction-time.

**Comment by mccalluc** [comment]
The Polars API is the preferred way to work with dataframes since 0.10, and we'll be deprecating the older dataframe methods: we won't be putting any work here.

If I do something like this, ie selecting the wrong column:
```
        context.query()
        .select(pl.col("no-such-column").fill_null(2.0).dp.sum((0, 3)))
        .release()
        .collect()
```
I get a reasonable error message:
```
E       opendp.mod.OpenDPException:
E         MakeTransformation("expression must span exactly one column, but expression spans 0 columns")
```
so I think we can close this.

- ... but I've opened #1937 to improve the usability of this particular example.
