### ISSUE TITLE
Release process tweaks

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#601]
Tweaks that could be made in the release process (noticed in 0.6.0 and 0.6.1):

* `release_tool.py init -t patch` should use release branch for ref, not main
* `release_tool.py preflight` should install opendp with `run_command`, not `run_command_with_retries`
* `release_tool.py {preflight|postflight}` should run all tests, not just `tools/test.py`
* `release_tool.py watch` needs better logic to find the right workflow (and possibly a pause/retries)
* Remove `toml` from `tools/requirements-publish_tool.py`

**Comment by Shoeboxam** [comment]
There is another issue in the order of operations. All links, even on 0.6.1, currently point to latest. 

The rust crate needs to be rebuilt with the updated version number, and the versions need to be set before tagging a release, in order for the links throughout the system to point to a versioned file, instead of latest.

**Comment by andrewvyrros** [comment]
Most of this is obviated by the new workflows in #880, as `channel_tool.py` (formerly `release_tool.py`) is much simplified, and most of the work happens in the new workflows.

The issue with the version number in Rust crate is covered by #880.
