### ISSUE TITLE
0.6.2 release preparation

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#631]

**Comment by andrewvyrros** [comment]
Build issues discovered when trying RC:

### `rustup` fails with "Device or resource busy"
https://github.com/opendp/opendp/actions/runs/4108583411/jobs/7089441264

Seems like installation needs to settle before new `rustup` is ready. Possible cause: https://github.com/rust-lang/rustup/issues/3189

### `cargo login` fails with "error: please provide a non-empty token"
https://github.com/opendp/opendp/actions/runs/4108583411/jobs/7089441416

Looks like we have a redundant `cargo login`, not needed because we already have the token in hand. Possible change that made this fail: https://github.com/rust-lang/cargo/pull/11145
