### ISSUE TITLE
Links in "New Contribution" template are dead

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#904]
https://github.com/opendp/opendp/blob/main/.github/ISSUE_TEMPLATE/new-contribution.md

The links in this template are dead. Might instead reference https://opendp.org/contribute or https://docs.opendp.org/en/beta/contributor/contribution-process.html ?

> How exciting!
> 
> Please review the following link for information to include in your issue:
> https://docs.opendp.org/en/latest/contributor/intro.html#code-and-proof-contributions
> 
> We will try to get back with you shortly.
> 
> In the meantime, you might want to review the contribution process:  
> https://docs.opendp.org/en/latest/contributor/contribution-process.html  
> (and start getting your development environment set up)

**Comment by Shoeboxam** [comment]
This was caused by https://github.com/opendp/opendp/pull/880.
I think both links should be the same, but point to nightly:

- https://docs.opendp.org/en/nightly/contributor/intro.html#code-and-proof-contributions
- https://docs.opendp.org/en/nightly/contributor/contribution-process.html

Might be a good place to advertise the Slack as well:
https://join.slack.com/t/opendp/shared_invite/zt-zw7o1k2s-dHg8NQE8WTfAGFnN_cwomA

(of which you are welcome to join!)

Thanks for catching this. More generally, all docs.opendp.org/en/latest/ links are now broken.

**Comment by Shoeboxam** [comment]
Yikes, thanks for double-checking my links. Another benefit of your suggestion is it would remove some un-tested links.
